added the error handling for different flags

diff --git a/weburl b/weburl
--- a/weburl
+++ b/weburl
@@ -11,9 +11,13 @@ case "$url" in
   while getopts ":f" opt; do
     case ${opt} in
       f ) #store the output to a file when user enters the flag -f
+          target=$OPTARG
           wget -O weblinks "$url" #download the html file from the url provided the store it to the weblinks file
           cat weblinks | grep -Eoi "(http|https)://[a-zA-Z0-9./]*" | sort -u > display
-        cat display #displays the output
+          cat display #displays the output
+        ;;
+           #propmpts a user an error message if they enter different flags
+      \? ) echo "Invalid option: $OPTARG use: [-f]" 1>&2 
         ;;
     esac
   done
@@ -21,7 +25,7 @@ case "$url" in
 #checks if the user provides any flag if not it will run this code
 if [[ $OPTIND -eq 1 ]] ; then 
           wget -O weblinks "$url" #download the html file from the url provided then store it to the weblinks file
-          cat weblinks | grep -Eoi "(http|https)://[a-zA-Z0-9./]*" | sort -u; fi
+          cat weblinks | grep -Eoi "(http|https)://[a-zA-Z0-9./]*" | sort -u; fi #displays the content
 shift $((OPTIND -1 )) #removes the options that have already been handled from 
   ;;
 esac
